baseURL: "https://jiasong-duan.github.io" 
title: Jiasong Duan
 pagerSize = 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        #- name: Books
        #  url: books/
        #  weight: 5 
        - name: Projects
          url: projects/
          weight: 2
        - name: Publications
          url: publications/
          weight: 3
        - name: Teaching
          url: teaching/
          weight: 4
        - name: CV
          url: cv/
          weight: 5
        #- name: Data
        #  url: data/
        #  weight: 4
        #- name: Blog
        #  url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #  weight: 6

params:
    description: |
        <p>I am a fifth-year Ph.D. student in statistics at the University of South Carolina. I am expecting to graduate in June 2026.</p>

        <p>My research focuses on the analysis of high-dimensional data and complex data, as well as on multidisciplinary collaborations. ...</p>
    author: Jiasong Duan
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jiasong Duan
          subtitle: "I am a fifth year PhD student in statistics at the University of South Carolina. I am expecting to graduate in June 2026. 
          
          My research focuses on the analysis of high-dimensional data and of complex data, as well as on multidisciplinary collaborations. Specifically, I work on variable selection 
          for heavy-tailed and skewed response, network estimation for non-Gaussian data, and collaborations in public health and biology. I am also interested in artificial intelligence techniques and their integration with statistical methodology."
          imageUrl: "jiasong_duan.jpg"
          imageWidth: 175
          imageHeight: 160
          imageTitle: 
          buttons:
            - name: Projects
              url: projects/
            - name: Publications
              url: publications/
            - name: Teaching
              url: teaching/
            - name: CV
              url: cv/
            #- name: Tags
            #  url: tags/
            #- name: Archive
            #  url: archive/
            #- name: Blog
            #  url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        #- name: CV
        #  url: Curriculum vitae of Jiasong Duan.pdf
        - name: Email
          url: mailto:duan.jiasong@email.sc.edu
        #- name: Zoom
        #  url: https://www.zoom.us/my/igelfeld
        #- name: Location
        #  url: location/
        #- name: Office Hours
        #  url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=GilU6SgAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/Jiasong-Duan
        #- name: Substack
        #  url: https://pmichaillat.substack.com
        #- name: YouTube
        #  url: https://www.youtube.com/@alexandermccallsmithoffici9000
        #- name: Twitter
        #  url: https://twitter.com/McCallSmith
        - name: Linkedin
          url: https://www.linkedin.com/in/jiasong-duan-050598142

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jiasong Duan"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2