baseURL: "https://jiasong-duan.github.io" 
title: Jiasong Duan
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        #- name: Books
        #  url: books/
        #  weight: 5 
        - name: Papers
          url: papers/
          weight: 2
        - name: Projects
          url: projects/
          weight: 3
        - name: Publications
          url: publications/
          weight: 4
        #- name: Courses
        #  url: courses/
        #  weight: 3
        #- name: Data
        #  url: data/
        #  weight: 4 
        #- name: Blog
        #  url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
        #  weight: 6

params:
    description: "I am a doctoral student in statistics at the University of South Carolina. My research interest variable selection, network analysis, high-dimensional analysis, and Omic analysis. I am expecting to graduate in May 2026."
    author: Jiasong Duan
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jiasong Duan
          subtitle: "I am a doctoral student in statistics at the University of South Carolina. My research interest variable selection, network analysis, high-dimensional analysis, and Omic analysis. I am expecting to graduate in May 2026."
          imageUrl: "jiasong_duan.jpg"
          imageWidth: 175
          imageHeight: 160
          imageTitle: 
          buttons:
            - name: Papers
              url: papers/
            - name: Projects
              url: projects/
            - name: Publications
              url: publications/
            #- name: Books
            #  url: books/
            #- name: Tags
            #  url: tags/
            #- name: Archive
            #  url: archive/
            #- name: Blog
            #  url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:duan.jiasong@yahoo.com
        #- name: Zoom
        #  url: https://www.zoom.us/my/igelfeld
        #- name: Location
        #  url: location/
        #- name: Office Hours
        #  url: officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=GilU6SgAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/Jiasong-Duan
        #- name: Substack
        #  url: https://pmichaillat.substack.com
        #- name: YouTube
        #  url: https://www.youtube.com/@alexandermccallsmithoffici9000
        #- name: Twitter
        #  url: https://twitter.com/McCallSmith
        - name: Linkedin
          url: https://www.linkedin.com/in/jiasong-duan-050598142

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jiasong Duan"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2